import { useCallback, useEffect, useState } from "react";
import toast from "react-hot-toast";
import { Loader2, Tag, Trash2 } from "lucide-react";
import api from "../Api/axios";

export default function AdminCoupons() {
  const [coupons, setCoupons] = useState([]); const [loading, setLoading] = useState(true);
  const [form, setForm] = useState({ code: "", type: "percent", value: "", minimum_amount: "", usage_limit: "" });
  const load = useCallback(async () => { try { const { data } = await api.get("/api/admin/coupons"); setCoupons(data.data || []); } catch { toast.error("Chargement impossible"); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const create = async (event) => { event.preventDefault(); try { await api.post("/api/admin/coupons", { ...form, code: form.code.toUpperCase(), minimum_amount: form.minimum_amount || 0, usage_limit: form.usage_limit || null }); setForm({ code: "", type: "percent", value: "", minimum_amount: "", usage_limit: "" }); toast.success("Code promotionnel créé"); load(); } catch (error) { toast.error(error.response?.data?.message || "Création impossible"); } };
  const remove = async (id) => { if (!window.confirm("Supprimer ce code ?")) return; await api.delete(`/api/admin/coupons/${id}`); toast.success("Code supprimé"); load(); };
  return <div className="max-w-6xl mx-auto space-y-6"><div><h1 className="text-2xl font-bold flex gap-3 items-center"><Tag className="text-indigo-600" /> Promotions</h1><p className="text-sm text-gray-500">Créez des codes promotionnels utilisables lors du checkout.</p></div><form onSubmit={create} className="bg-white rounded-2xl border p-5 grid md:grid-cols-5 gap-3"><input required placeholder="CODE10" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} className="border rounded-lg p-2" /><select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })} className="border rounded-lg p-2"><option value="percent">Pourcentage</option><option value="fixed">Montant DH</option></select><input required type="number" min="0.01" step="0.01" placeholder="Valeur" value={form.value} onChange={(e) => setForm({ ...form, value: e.target.value })} className="border rounded-lg p-2" /><input type="number" min="0" placeholder="Minimum (DH)" value={form.minimum_amount} onChange={(e) => setForm({ ...form, minimum_amount: e.target.value })} className="border rounded-lg p-2" /><button className="bg-indigo-600 text-white rounded-lg font-medium">Créer</button></form><div className="bg-white rounded-2xl border overflow-x-auto"><table className="w-full text-left"><thead className="bg-gray-50 text-xs uppercase text-gray-400"><tr><th className="p-4">Code</th><th className="p-4">Réduction</th><th className="p-4">Utilisations</th><th className="p-4"></th></tr></thead><tbody className="divide-y">{loading ? <tr><td colSpan="4" className="p-10 text-center"><Loader2 className="animate-spin inline text-indigo-600" /></td></tr> : coupons.map((coupon) => <tr key={coupon.id}><td className="p-4 font-bold">{coupon.code}</td><td className="p-4">{coupon.type === "percent" ? `${coupon.value}%` : `${coupon.value} DH`}</td><td className="p-4">{coupon.used_count}{coupon.usage_limit ? ` / ${coupon.usage_limit}` : ""}</td><td className="p-4 text-right"><button onClick={() => remove(coupon.id)} className="text-red-500"><Trash2 size={18} /></button></td></tr>)}</tbody></table></div></div>;
}
