import { createContext, useContext, useEffect, useMemo, useState } from "react";
import storefront from "../locales/storefront";
import cash from "../locales/cash";
import payment from "../locales/payment";
import premium from "../locales/premium";

const dictionaries = {
  fr: {
    home: "Accueil",
    products: "Produits",
    favorites: "Favoris",
    support: "Support",
    deliveries: "Livraisons",
    cart: "Panier",
    login: "Connexion",
    register: "S’inscrire",
    profile: "Mon profil",
    orders: "Mes commandes",
    password: "Mot de passe",
    logout: "Déconnexion",
    notifications: "Notifications",
    markAllRead: "Tout marquer comme lu",
    noNotifications: "Aucune notification.",
    account: "Mon compte",
    language: "Langue",
    theme: "Thème",
    light: "Jour",
    dark: "Nuit",
    loading: "Chargement…",
    refresh: "Actualiser",
    close: "Fermer",
    all: "Toutes",
    name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    address: "Adresse",
    subject: "Sujet",
    message: "Message",
    total: "Total",
    previous: "Précédent",
    next: "Suivant",
    firstPage: "Première page",
    lastPage: "Dernière page",
    page: "Page {page}",
    client: "Client",
    product: "Produit",
    category: "Catégorie",
    availability: "Disponibilité",
    searchProducts: "Rechercher un produit…",
    catalog: "Catalogue",
    promos: "Promos",
    newProducts: "Nouveautés",
    addToCart: "Ajouter au panier",
    outOfStock: "Rupture",
    soonAvailable: "Bientôt disponible",
    unavailable: "Indisponible",
    inStock: "En stock",
    inStockCount: "En stock : {count}",
    lowStockCount: "Stock faible : {count}",
    productNotFound: "Produit introuvable",
    productUnavailable: "Produit indisponible",
    productAddedCart: "Produit ajouté au panier",
    loginForFavorites: "Connectez-vous avec un compte client pour utiliser les favoris",
    removedFromFavorites: "Retiré des favoris",
    addedToFavorites: "Ajouté aux favoris",
    favoriteUpdateError: "Impossible de modifier les favoris",
    descriptionEmpty: "Aucune description disponible.",
    customerReviews: "Avis clients",
    shareExperience: "Partagez votre expérience (facultatif)",
    publishReview: "Publier mon avis",
    thanksReview: "Merci pour votre avis",
    reviewSaveError: "Votre avis ne peut pas être enregistré",
    noReviews: "Aucun avis pour le moment.",
    sameCategory: "Même catégorie",
    similarProducts: "Produits similaires",
    backToProducts: "Retour aux produits",
    productVideo: "Vidéo du produit",
    optionPriceAdapted: "Prix adapté à l’option choisie.",
    chooseOptions: "Choisissez vos options",
    variantHelp: "Couleur, taille, poids, capacité ou lot selon ce produit.",
    maxOrderQuantity: "Vous pouvez commander jusqu’à {count} unité(s).",
    orderNow: "Commander maintenant",
    securePayment: "Paiement sécurisé",
    pickupOrDelivery: "Retrait ou livraison",
    afterOrderSupport: "Support après commande",
    longDescription: "Description longue",
    detailsBeforeBuying: "Tous les détails avant d’acheter",
    longDescriptionFallback: "Aucune description détaillée pour le moment. Ajoutez plus d’informations dans l’administration : matière, dimensions, contenu du lot, garantie, conservation ou compatibilité selon le produit.",
    quickGuide: "Guide rapide",
    quickGuideOptions: "Vérifiez les options avant d’ajouter au panier.",
    quickGuidePromos: "Les promotions affichent l’ancien prix barré.",
    quickGuideDelivery: "Livraison gratuite si le produit ou votre fidélité est éligible.",
    purchaseInfo: "Informations d’achat",
    selectedOptions: "Options sélectionnées",
    errorTitle: "Quelque chose s’est mal passé",
    errorMessage: "Rechargez la page ou revenez à l’accueil.",
    backHome: "Retour à l’accueil",
    heroTitle: "Votre magasin complet, dans votre poche.",
    heroSubtitle: "Alimentation, maison, multimédia et offres du moment avec une expérience rapide sur téléphone, tablette et ordinateur.",
    fastProcessing: "Traitement rapide",
    twoModes: "2 modes",
    organizedCatalog: "Catalogue organisé",
    organizedCatalogText: "Nouveautés, catégories et produits similaires.",
    deliveryPickupTitle: "Livraison ou retrait",
    deliveryPickupText: "Adresse du client, position du magasin et suivi de la commande.",
    latestProducts: "Nouveaux produits",
    latestProductsSubtitle: "Les derniers produits ajoutés à la boutique",
    featuredProducts: "Sélection AliShop",
    featuredProductsSubtitle: "Les produits mis en avant par notre équipe",
    promoProducts: "Produits en promotion",
    promoProductsSubtitle: "Offres à prix réduit",
    noActivePromos: "Aucune promotion active pour le moment.",
    yourFavorites: "Vos favoris",
    yourFavoritesSubtitle: "Les produits que vous avez gardés sous la main",
    noFavoriteHome: "Vous n’avez pas encore de favoris.",
    viewAll: "Voir tout",
    noProductAvailable: "Aucun produit disponible.",
    searchHero: "Rechercher un produit, une catégorie…",
    exploreProducts: "Explorer les produits",
    needHelp: "Besoin d’aide ?",
    deliveryPickup: "Livraison / retrait",
    catalogTitle: "Trouvez vite le bon produit.",
    catalogSubtitle: "Parcourez les nouveautés, les promotions et les catégories avec une expérience rapide sur mobile.",
    filters: "Filtres",
    displayedProducts: "{count} produit(s) affiché(s)",
    catalogCount: "{count} produit(s) trouvé(s)",
    productsRange: "{from}–{to} sur {total} produits",
    perPage: "{count} par page",
    removePromoFilter: "Retirer le filtre promotions",
    emptyCart: "Votre panier est vide",
    emptyCartDescription: "Explorez notre catalogue et ajoutez les produits qui vous plaisent. Votre sélection restera disponible pendant vos achats.",
    cartBenefitChoice: "Produits et offres sélectionnés",
    cartLoadError: "Impossible de charger votre panier",
    cartLoadErrorHelp: "Vérifiez votre connexion puis réessayez. Aucun article enregistré ne sera supprimé.",
    quantityError: "Quantité impossible",
    productRemoved: "Produit supprimé",
    seeProducts: "Voir les produits",
    viewDetails: "Voir les détails",
    summary: "Résumé",
    subtotal: "Sous-total",
    estimatedDelivery: "Livraison estimée",
    deliveryFee: "Frais de livraison",
    estimatedDeliveryFee: "Estimation de la livraison",
    deliveryDistance: "Distance de livraison",
    deliveryCalculatedCheckout: "Les frais de livraison sont calculés lors de la commande selon le trajet.",
    deliveryFeeEstimated: "30 DH est seulement une estimation sans GPS. Activez votre position pour afficher le vrai prix du trajet.",
    deliveryFeeConfirmed: "Frais calculés et confirmés : {fee} DH.",
    casaOnlyDelivery: "Livraison disponible seulement à Casablanca pour le moment.",
    deliveryTimeSlot: "Disponibilité pour la livraison",
    deliveryTimeSlotHelp: "Choisissez le moment où vous êtes disponible. Le livreur utilisera ce créneau pour passer chez vous.",
    deliverySlotRequired: "Choisissez votre disponibilité pour la livraison.",
    slotMorning: "08:00 - 12:00",
    slotAfternoon: "12:00 - 18:00",
    slotEvening: "18:00 - 21:00",
    slotMorningHelp: "Matin : pratique si vous êtes disponible avant midi.",
    slotAfternoonHelp: "Après-midi : le choix le plus flexible pour la plupart des clients.",
    slotEveningHelp: "Soir : pratique après le travail ou les cours.",
    cardRequiredLargeOrder: "Paiement par carte obligatoire pour les commandes de 5 000 DH ou plus.",
    deliveryDistancePrice: "Trajet calculé : {distance} km, frais de {fee} DH.",
    freeDeliveryApplied: "Livraison gratuite appliquée par la boutique.",
    freeDeliveryProduct: "Livraison gratuite",
    freeDeliveryProductHint: "0 DH si le panier contient uniquement des produits éligibles.",
    pickupFree: "Retrait magasin gratuit.",
    checkout: "Finalisation de la commande",
    placeOrder: "Passer la commande",
    confirmOrder: "Confirmer la commande",
    homeDelivery: "Livraison à domicile",
    fulfillmentMode: "Mode de réception",
    pickup: "Retrait en magasin",
    deliveryAddress: "Adresse de livraison",
    addressRequired: "Adresse obligatoire",
    phoneRequired: "Téléphone obligatoire",
    fieldRequired: "Champ obligatoire",
    geolocationUnsupported: "La géolocalisation n’est pas prise en charge",
    locationError: "Impossible d’obtenir votre position",
    cmiRedirecting: "Redirection vers le paiement sécurisé CMI",
    orderConfirmed: "Commande confirmée",
    checkoutError: "Erreur lors de la commande",
    checkoutAccountTitle: "Connectez-vous pour confirmer la commande",
    checkoutAccountText: "Votre panier reste ici. Connectez-vous ou créez un compte, puis la commande sera confirmée directement.",
    continueAsLogin: "J’ai déjà un compte",
    continueAsRegister: "Créer mon compte",
    authAndOrder: "Se connecter et commander",
    registerAndOrder: "Créer le compte et commander",
    authRequiredCheckout: "Connectez-vous ou créez un compte pour confirmer la commande.",
    customerOnlyCheckout: "Seul un compte client peut passer commande.",
    retryIn: "Réessayez dans {seconds} s",
    useMyLocation: "Utiliser ma position pour la livraison",
    savedLocation: "Position enregistrée",
    cashPayment: "Paiement à la livraison",
    cardPayment: "Paiement par carte",
    cmiSecure: "Paiement sécurisé par CMI",
    cmiRedirect: "Après confirmation, vous serez redirigé vers la page bancaire CMI pour payer par carte.",
    coupon: "Code promotionnel (facultatif)",
    supportClient: "Support client",
    supportProblem: "Problème",
    requestProduct: "Demander un produit",
    productRequestSubject: "Produit demandé",
    wantedProductName: "Nom du produit souhaité",
    wantedProductPhoto: "Photo du produit si possible",
    supportTitle: "Nous sommes là quand ça bloque.",
    supportSubtitle: "Envoyez votre demande, suivez son état et recevez la réponse de l’administration directement ici.",
    priority: "Priorité",
    low: "Faible",
    normal: "Normal",
    high: "Important",
    urgent: "Urgent",
    yourMessage: "Votre message…",
    sending: "Envoi…",
    sendMessage: "Envoyer le message",
    messageSent: "Message envoyé. Nous vous répondrons rapidement.",
    messageSendError: "Impossible d’envoyer le message",
    supportLoadError: "Impossible de charger vos demandes d’assistance",
    myRequests: "Mes demandes",
    supportHistory: "Historique de l’assistance",
    loginToSeeSupport: "Connectez-vous pour voir l’historique de vos demandes.",
    noSupportMessages: "Aucune demande pour le moment.",
    supportReply: "Réponse du support",
    markResolved: "Marquer comme résolu",
    ticketClosed: "Demande fermée",
    closeTicketError: "Impossible de fermer cette demande",
    open: "Ouvert",
    in_progress: "En traitement",
    answered: "Répondu",
    closed: "Fermé",
    deliverySpace: "Espace livreur",
    myDeliveries: "Mes livraisons",
    activeDeliveries: "{count} livraison(s) active(s)",
    deliveryLoadError: "Erreur lors du chargement des livraisons",
    loadingDeliveries: "Chargement des livraisons…",
    noAssignedOrders: "Aucune commande ne vous est assignée.",
    orderNumber: "Commande {id}",
    pending: "En attente",
    preparing: "Préparation",
    shipping: "Livraison en cours",
    delivered: "Livrée",
    available: "Disponible",
    contact: "Contact",
    phoneUnavailable: "Téléphone indisponible",
    openRoute: "Ouvrir l’itinéraire",
    packageContent: "Contenu du colis",
    missionAvailable: "Mission disponible pour tous les livreurs. Le premier qui accepte la prend.",
    acceptDelivery: "Accepter cette livraison",
    accepting: "Acceptation…",
    deliveryAccepted: "Livraison acceptée",
    deliveryUnavailable: "Cette livraison n’est plus disponible",
    receiverName: "Nom du réceptionnaire",
    photoOnSite: "Prendre une photo sur place",
    cameraOrGallery: "Caméra du téléphone ou galerie",
    deliveryNote: "Note de livraison (facultative)",
    confirmDelivery: "Confirmer la livraison",
    processing: "Traitement…",
    deliveryConfirmed: "Livraison confirmée",
    deliveryDone: "Livraison effectuée",
    proofRequired: "Nom du réceptionnaire et photo sur place obligatoires",
    updateError: "Erreur de mise à jour",
    orderTracking: "Suivi client",
    loadOrdersError: "Erreur lors du chargement des commandes",
    noOrders: "Aucune commande",
    storePickup: "Retrait en magasin",
    delivery: "Livraison",
    deliveryTracking: "Suivi de livraison",
    received: "Reçue",
    downloadReceipt: "Télécharger le reçu PDF",
    receiptError: "Impossible de télécharger le reçu",
    pickupInStore: "Retrait en magasin",
    deliveryProof: "Preuve de livraison",
    receivedBy: "Réceptionnée par : {name}",
    paymentConfirmed: "Paiement confirmé",
    paymentNotConfirmed: "Paiement non confirmé",
    paymentSuccessMessage: "Votre paiement CMI{order} a été validé.",
    paymentFailureMessage: "La transaction par carte a échoué ou a été annulée. Vous pouvez vérifier vos commandes ou recommencer la finalisation.",
    paymentFailureCashOption: "Si le paiement par carte échoue encore, vous pouvez refaire la commande avec paiement à la livraison si le total est inférieur à 5 000 DH.",
    cancelOrder: "Annuler la commande",
    orderCancelled: "Commande annulée",
    refunded: "Remboursée",
    forOrder: " pour la commande #{id}",
    viewOrders: "Voir mes commandes",
    continueShopping: "Continuer mes achats",
    favoriteSelection: "Votre sélection",
    favoriteProducts: "Produits favoris",
    noFavorites: "Aucun favori pour le moment.",
    loginTitle: "Connexion",
    loginSubtitle: "Retrouvez votre panier, vos commandes et vos favoris.",
    loginTrustText: "Panier conservé, commandes sécurisées, support rapide.",
    forgotPassword: "Mot de passe oublié ?",
    loginAction: "Se connecter",
    loginLoading: "Connexion…",
    loginSuccess: "Connexion réussie",
    loginError: "Erreur de connexion",
    noAccount: "Pas de compte ?",
    createAccount: "Créer un compte",
    registerSubtitle: "Votre panier sera conservé après votre inscription.",
    passwordConfirm: "Confirmer le mot de passe",
    addressOptional: "Adresse (optionnel)",
    passwordTooShort: "Le mot de passe doit contenir au moins 8 caractères",
    passwordMismatch: "Les mots de passe ne correspondent pas",
    registerLoading: "Création...",
    accountCreated: "Compte créé avec succès",
    registerError: "Erreur lors de l’inscription",
    alreadyAccount: "Déjà un compte ?",
    navigation: "Navigation",
    mainMenu: "Menu principal",
    dashboard: "Dashboard",
    categories: "Catégories",
    users: "Utilisateurs",
    adminAccount: "Compte administrateur",
    adminSupportWorkflow: "Workflow messages clients",
    adminSupportSubtitle: "Priorisez, répondez et fermez les demandes depuis l’administration.",
    supportUpdated: "Support mis à jour",
    supportAdminLoadError: "Impossible de charger le support",
    updateImpossible: "Mise à jour impossible",
    lastReply: "Dernière réponse",
    writeCustomerReply: "Écrire une réponse au client…",
    sendReply: "Envoyer la réponse",
    noCustomerMessage: "Aucun message client.",
    profileUpdated: "Profil mis à jour",
    profileUpdateError: "Erreur lors de la mise à jour",
    editProfile: "Modifier le profil",
    changePassword: "Changer le mot de passe",
    currentPassword: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    showPasswords: "Afficher les mots de passe",
    update: "Mettre à jour",
    enterEmail: "Veuillez saisir votre e-mail",
    resetEmailSent: "E-mail de réinitialisation envoyé",
    resetPassword: "Réinitialiser le mot de passe",
    resetLoading: "Réinitialisation…",
    passwordResetSuccess: "Mot de passe réinitialisé",
    resetError: "Erreur lors de la réinitialisation",
    send: "Envoyer",
    yourEmail: "Votre e-mail",
    store: "Magasin",
    footerText: "Boutique e-commerce moderne à Casablanca : promotions, retrait en magasin, livraison et suivi de commande.",
    rightsReserved: "Tous droits réservés.",
    cookieText: "Nous utilisons des statistiques anonymes pour comprendre les produits consultés et améliorer le site.",
    accept: "Accepter",
    decline: "Refuser",
    gpsMissing: "Position GPS non fournie par le client.",
  },
  en: {
    home: "Home",
    products: "Products",
    favorites: "Favorites",
    support: "Support",
    deliveries: "Deliveries",
    cart: "Cart",
    login: "Login",
    register: "Sign up",
    profile: "My profile",
    orders: "My orders",
    password: "Password",
    logout: "Log out",
    notifications: "Notifications",
    markAllRead: "Mark all read",
    noNotifications: "No notifications.",
    account: "My account",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    loading: "Loading...",
    refresh: "Refresh",
    close: "Close",
    all: "All",
    name: "Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    subject: "Subject",
    message: "Message",
    total: "Total",
    previous: "Previous",
    next: "Next",
    firstPage: "First page",
    lastPage: "Last page",
    page: "Page {page}",
    client: "Customer",
    product: "Product",
    category: "Category",
    availability: "Availability",
    searchProducts: "Search for a product...",
    catalog: "Catalog",
    promos: "Deals",
    newProducts: "New arrivals",
    addToCart: "Add to cart",
    outOfStock: "Out of stock",
    soonAvailable: "Soon available",
    unavailable: "Unavailable",
    inStock: "In stock",
    inStockCount: "In stock: {count}",
    lowStockCount: "Low stock: {count}",
    productNotFound: "Product not found",
    productUnavailable: "Product unavailable",
    productAddedCart: "Product added to cart",
    loginForFavorites: "Log in with a customer account to use favorites",
    removedFromFavorites: "Removed from favorites",
    addedToFavorites: "Added to favorites",
    favoriteUpdateError: "Unable to update favorites",
    descriptionEmpty: "No description available.",
    customerReviews: "Customer reviews",
    shareExperience: "Share your experience (optional)",
    publishReview: "Publish my review",
    thanksReview: "Thanks for your review",
    reviewSaveError: "Your review could not be saved",
    noReviews: "No reviews yet.",
    sameCategory: "Same category",
    similarProducts: "Similar products",
    backToProducts: "Back to products",
    productVideo: "Product video",
    optionPriceAdapted: "Price updated for the selected option.",
    chooseOptions: "Choose your options",
    variantHelp: "Color, size, weight, capacity or pack depending on this product.",
    maxOrderQuantity: "You can order up to {count} unit(s).",
    orderNow: "Order now",
    securePayment: "Secure payment",
    pickupOrDelivery: "Pickup or delivery",
    afterOrderSupport: "After-order support",
    longDescription: "Long description",
    detailsBeforeBuying: "All details before buying",
    longDescriptionFallback: "No detailed description yet. Add more information in the admin area: material, dimensions, pack content, warranty, storage or compatibility depending on the product.",
    quickGuide: "Quick guide",
    quickGuideOptions: "Check the options before adding to cart.",
    quickGuidePromos: "Promotions show the old crossed-out price.",
    quickGuideDelivery: "Free delivery applies when the product or your loyalty is eligible.",
    purchaseInfo: "Purchase information",
    selectedOptions: "Selected options",
    errorTitle: "Something went wrong",
    errorMessage: "Refresh the page or go back home.",
    backHome: "Back home",
    heroTitle: "Your full store, right in your pocket.",
    heroSubtitle: "Groceries, home, multimedia and current deals with a fast experience on phone, tablet and desktop.",
    fastProcessing: "Fast processing",
    twoModes: "2 modes",
    organizedCatalog: "Organized catalog",
    organizedCatalogText: "New arrivals, categories and similar products.",
    deliveryPickupTitle: "Delivery or pickup",
    deliveryPickupText: "Customer address, store location and order tracking.",
    latestProducts: "New products",
    latestProductsSubtitle: "The latest products added to the store",
    featuredProducts: "AliShop selection",
    featuredProductsSubtitle: "Products selected by our team",
    promoProducts: "Products on sale",
    promoProductsSubtitle: "Offers with reduced prices",
    noActivePromos: "No active deal right now.",
    yourFavorites: "Your favorites",
    yourFavoritesSubtitle: "Products you kept close at hand",
    noFavoriteHome: "You do not have favorites yet.",
    viewAll: "View all",
    noProductAvailable: "No product available.",
    searchHero: "Search for a product or category...",
    exploreProducts: "Explore products",
    needHelp: "Need help?",
    deliveryPickup: "Delivery / pickup",
    catalogTitle: "Find the right product fast.",
    catalogSubtitle: "Browse new arrivals, deals and categories with a fast mobile experience.",
    filters: "Filters",
    displayedProducts: "{count} product(s) displayed",
    catalogCount: "{count} product(s) found",
    productsRange: "{from}-{to} of {total} products",
    perPage: "{count} per page",
    removePromoFilter: "Remove deals filter",
    emptyCart: "Your cart is empty",
    emptyCartDescription: "Explore our catalog and add the products you love. Your selection stays available while you shop.",
    cartBenefitChoice: "Curated products and deals",
    cartLoadError: "Unable to load your cart",
    cartLoadErrorHelp: "Check your connection and try again. No saved item will be removed.",
    quantityError: "Quantity update unavailable",
    productRemoved: "Product removed",
    seeProducts: "View products",
    viewDetails: "View details",
    summary: "Summary",
    subtotal: "Subtotal",
    estimatedDelivery: "Estimated delivery",
    deliveryFee: "Delivery fee",
    estimatedDeliveryFee: "Estimated delivery",
    deliveryDistance: "Delivery distance",
    deliveryCalculatedCheckout: "Delivery fees are calculated at checkout based on the trip.",
    deliveryFeeEstimated: "30 DH is only an estimate without GPS. Use your location to show the real trip price.",
    deliveryFeeConfirmed: "Delivery fee calculated and confirmed: {fee} DH.",
    casaOnlyDelivery: "Delivery is currently available only in Casablanca.",
    deliveryTimeSlot: "Delivery availability",
    deliveryTimeSlotHelp: "Choose when you are available. The courier will use this time window for delivery.",
    deliverySlotRequired: "Choose your delivery availability.",
    slotMorning: "08:00 - 12:00",
    slotAfternoon: "12:00 - 18:00",
    slotEvening: "18:00 - 21:00",
    slotMorningHelp: "Morning: useful if you are available before noon.",
    slotAfternoonHelp: "Afternoon: the most flexible choice for most customers.",
    slotEveningHelp: "Evening: useful after work or classes.",
    cardRequiredLargeOrder: "Card payment is required for orders of 5000 DH or more.",
    deliveryDistancePrice: "Calculated trip: {distance} km, fee {fee} DH.",
    freeDeliveryApplied: "Free delivery applied by the store.",
    freeDeliveryProduct: "Free delivery",
    freeDeliveryProductHint: "0 DH if the cart only contains eligible products.",
    pickupFree: "Store pickup is free.",
    checkout: "Checkout",
    placeOrder: "Place order",
    confirmOrder: "Confirm order",
    homeDelivery: "Home delivery",
    fulfillmentMode: "Fulfilment method",
    pickup: "Store pickup",
    deliveryAddress: "Delivery address",
    addressRequired: "Address is required",
    phoneRequired: "Phone is required",
    fieldRequired: "Required field",
    geolocationUnsupported: "Geolocation is not supported",
    locationError: "Unable to get your location",
    cmiRedirecting: "Redirecting to secure CMI payment",
    orderConfirmed: "Order confirmed",
    checkoutError: "Checkout error",
    checkoutAccountTitle: "Log in to confirm",
    checkoutAccountText: "Your cart stays here. Log in or create an account, then the order will be confirmed directly.",
    continueAsLogin: "I already have an account",
    continueAsRegister: "Create my account",
    authAndOrder: "Log in and order",
    registerAndOrder: "Create account and order",
    authRequiredCheckout: "Log in or create an account to confirm the order.",
    customerOnlyCheckout: "Only a customer account can place an order.",
    retryIn: "Try again in {seconds}s",
    useMyLocation: "Use my location for delivery",
    savedLocation: "Location saved",
    cashPayment: "Cash on delivery",
    cardPayment: "Card payment",
    cmiSecure: "Secure payment by CMI",
    cmiRedirect: "After confirmation, you will be redirected to the CMI bank page to pay by card.",
    coupon: "Promo code (optional)",
    supportClient: "Customer support",
    supportProblem: "Problem",
    requestProduct: "Request product",
    productRequestSubject: "Requested product",
    wantedProductName: "Wanted product name",
    wantedProductPhoto: "Product photo if possible",
    supportTitle: "We are here when something gets stuck.",
    supportSubtitle: "Send your request, track its status and receive the admin reply directly here.",
    priority: "Priority",
    low: "Low",
    normal: "Normal",
    high: "Important",
    urgent: "Urgent",
    yourMessage: "Your message...",
    sending: "Sending...",
    sendMessage: "Send message",
    messageSent: "Message sent. We will reply quickly.",
    messageSendError: "Unable to send the message",
    supportLoadError: "Unable to load your support requests",
    myRequests: "My requests",
    supportHistory: "Support history",
    loginToSeeSupport: "Log in to view your support request history.",
    noSupportMessages: "No requests yet.",
    supportReply: "Support reply",
    markResolved: "Mark as resolved",
    ticketClosed: "Request closed",
    closeTicketError: "Unable to close this request",
    open: "Open",
    in_progress: "In progress",
    answered: "Answered",
    closed: "Closed",
    deliverySpace: "Courier space",
    myDeliveries: "My deliveries",
    activeDeliveries: "{count} active delivery/deliveries",
    deliveryLoadError: "Error while loading deliveries",
    loadingDeliveries: "Loading deliveries...",
    noAssignedOrders: "No order is assigned to you.",
    orderNumber: "Order {id}",
    pending: "Pending",
    preparing: "Preparing",
    shipping: "Out for delivery",
    delivered: "Delivered",
    available: "Available",
    contact: "Contact",
    phoneUnavailable: "Phone unavailable",
    openRoute: "Open route",
    packageContent: "Package content",
    missionAvailable: "Mission available to all couriers. The first one to accept gets it.",
    acceptDelivery: "Accept this delivery",
    accepting: "Accepting...",
    deliveryAccepted: "Delivery accepted",
    deliveryUnavailable: "This delivery is no longer available",
    receiverName: "Receiver name",
    photoOnSite: "Take on-site photo",
    cameraOrGallery: "Phone camera or gallery",
    deliveryNote: "Delivery note (optional)",
    confirmDelivery: "Confirm delivery",
    processing: "Processing...",
    deliveryConfirmed: "Delivery confirmed",
    deliveryDone: "Delivery completed",
    proofRequired: "Receiver name and on-site photo are required",
    updateError: "Update error",
    orderTracking: "Customer tracking",
    loadOrdersError: "Error loading orders",
    noOrders: "No orders",
    storePickup: "Store pickup",
    delivery: "Delivery",
    deliveryTracking: "Delivery tracking",
    received: "Received",
    downloadReceipt: "Download PDF receipt",
    receiptError: "Unable to download receipt",
    pickupInStore: "Store pickup",
    deliveryProof: "Delivery proof",
    receivedBy: "Received by: {name}",
    paymentConfirmed: "Payment confirmed",
    paymentNotConfirmed: "Payment not confirmed",
    paymentSuccessMessage: "Your CMI payment{order} has been validated.",
    paymentFailureMessage: "The card transaction failed or was cancelled. You can check your orders or retry checkout.",
    paymentFailureCashOption: "If card payment fails again, you can reorder with cash on delivery when the total is under 5000 DH.",
    cancelOrder: "Cancel order",
    orderCancelled: "Order cancelled",
    refunded: "Refunded",
    forOrder: " for order #{id}",
    viewOrders: "View my orders",
    continueShopping: "Continue shopping",
    favoriteSelection: "Your selection",
    favoriteProducts: "Favorite products",
    noFavorites: "No favorites yet.",
    loginTitle: "Login",
    loginSubtitle: "Find your cart, orders and favorites.",
    loginTrustText: "Saved cart, secure orders, fast support.",
    forgotPassword: "Forgot password?",
    loginAction: "Log in",
    loginLoading: "Logging in...",
    loginSuccess: "Logged in successfully",
    loginError: "Login error",
    noAccount: "No account?",
    createAccount: "Create an account",
    registerSubtitle: "Your cart will be kept after sign-up.",
    passwordConfirm: "Confirm password",
    addressOptional: "Address (optional)",
    passwordTooShort: "Password must contain at least 8 characters",
    passwordMismatch: "Passwords do not match",
    registerLoading: "Creating...",
    accountCreated: "Account created successfully",
    registerError: "Sign-up error",
    alreadyAccount: "Already have an account?",
    navigation: "Navigation",
    mainMenu: "Main menu",
    dashboard: "Dashboard",
    categories: "Categories",
    users: "Users",
    adminAccount: "Administrator account",
    adminSupportWorkflow: "Customer message workflow",
    adminSupportSubtitle: "Prioritize, reply and close requests from admin.",
    supportUpdated: "Support updated",
    supportAdminLoadError: "Unable to load support",
    updateImpossible: "Update unavailable",
    lastReply: "Latest reply",
    writeCustomerReply: "Write a reply to the customer...",
    sendReply: "Send reply",
    noCustomerMessage: "No customer message.",
    profileUpdated: "Profile updated",
    profileUpdateError: "Error while updating profile",
    editProfile: "Edit profile",
    changePassword: "Change password",
    currentPassword: "Current password",
    newPassword: "New password",
    showPasswords: "Show passwords",
    update: "Update",
    enterEmail: "Please enter your email",
    resetEmailSent: "Reset email sent",
    resetPassword: "Reset password",
    resetLoading: "Resetting...",
    passwordResetSuccess: "Password reset successfully",
    resetError: "Error while resetting password",
    send: "Send",
    yourEmail: "Your email",
    store: "Store",
    footerText: "Modern e-commerce store in Casablanca: deals, pickup, delivery and order tracking.",
    rightsReserved: "All rights reserved.",
    cookieText: "We use anonymous analytics to understand viewed products and improve the website.",
    accept: "Accept",
    decline: "Decline",
    gpsMissing: "GPS position was not provided by the customer.",
  },
  ar: {
    home: "الرئيسية",
    products: "المنتجات",
    favorites: "المفضلة",
    support: "الدعم",
    deliveries: "التوصيلات",
    cart: "السلة",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    profile: "حسابي",
    orders: "طلباتي",
    password: "كلمة المرور",
    logout: "تسجيل الخروج",
    notifications: "الإشعارات",
    markAllRead: "تحديد الكل كمقروء",
    noNotifications: "لا توجد إشعارات.",
    account: "حسابي",
    language: "اللغة",
    theme: "المظهر",
    light: "نهاري",
    dark: "ليلي",
    loading: "جار التحميل...",
    refresh: "تحديث",
    close: "إغلاق",
    all: "الكل",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    address: "العنوان",
    subject: "الموضوع",
    message: "الرسالة",
    total: "المجموع",
    previous: "السابق",
    next: "التالي",
    firstPage: "الصفحة الأولى",
    lastPage: "الصفحة الأخيرة",
    page: "الصفحة {page}",
    client: "الزبون",
    product: "منتج",
    category: "القسم",
    availability: "التوفر",
    searchProducts: "ابحث عن منتج...",
    catalog: "الكتالوج",
    promos: "العروض",
    newProducts: "الجديد",
    addToCart: "أضف إلى السلة",
    outOfStock: "غير متوفر",
    unavailable: "غير متوفر",
    inStock: "متوفر",
    inStockCount: "متوفر: {count}",
    lowStockCount: "مخزون منخفض: {count}",
    productNotFound: "المنتج غير موجود",
    productUnavailable: "المنتج غير متوفر",
    productAddedCart: "تمت إضافة المنتج إلى السلة",
    loginForFavorites: "سجل الدخول بحساب زبون لاستعمال المفضلة",
    removedFromFavorites: "تمت الإزالة من المفضلة",
    addedToFavorites: "تمت الإضافة إلى المفضلة",
    favoriteUpdateError: "تعذر تحديث المفضلة",
    descriptionEmpty: "لا يوجد وصف متاح.",
    customerReviews: "آراء الزبناء",
    shareExperience: "شارك تجربتك (اختياري)",
    publishReview: "نشر رأيي",
    thanksReview: "شكرا على رأيك",
    reviewSaveError: "تعذر حفظ رأيك",
    noReviews: "لا توجد آراء حاليا.",
    sameCategory: "نفس القسم",
    similarProducts: "منتجات مشابهة",
    backToProducts: "العودة إلى المنتجات",
    productVideo: "فيديو المنتج",
    optionPriceAdapted: "تم تحديث السعر حسب الخيار المختار.",
    chooseOptions: "اختر الخيارات",
    variantHelp: "اللون أو المقاس أو الوزن أو السعة أو الباقة حسب نوع المنتج.",
    maxOrderQuantity: "يمكنك طلب حتى {count} وحدة.",
    orderNow: "اطلب الآن",
    securePayment: "دفع آمن",
    pickupOrDelivery: "استلام أو توصيل",
    afterOrderSupport: "دعم بعد الطلب",
    longDescription: "الوصف المفصل",
    detailsBeforeBuying: "كل التفاصيل قبل الشراء",
    longDescriptionFallback: "لا يوجد وصف مفصل حاليا. أضف معلومات أكثر من الإدارة: المادة، الأبعاد، محتوى الباقة، الضمان، طريقة الحفظ أو التوافق حسب المنتج.",
    quickGuide: "دليل سريع",
    quickGuideOptions: "تحقق من الخيارات قبل الإضافة إلى السلة.",
    quickGuidePromos: "العروض تظهر السعر القديم مشطوبا.",
    quickGuideDelivery: "يتم تطبيق التوصيل المجاني إذا كان المنتج أو وفاؤك مؤهلا.",
    purchaseInfo: "معلومات الشراء",
    selectedOptions: "الخيارات المختارة",
    errorTitle: "حدث خطأ",
    errorMessage: "أعد تحميل الصفحة أو ارجع إلى الرئيسية.",
    backHome: "العودة للرئيسية",
    heroTitle: "متجرك الكامل في جيبك.",
    heroSubtitle: "مواد غذائية، منزل، إلكترونيات وعروض اليوم بتجربة سريعة على الهاتف واللوحة والحاسوب.",
    fastProcessing: "معالجة سريعة",
    twoModes: "وضعان",
    organizedCatalog: "كتالوج منظم",
    organizedCatalogText: "منتجات جديدة، أقسام ومنتجات مشابهة.",
    deliveryPickupTitle: "توصيل أو استلام",
    deliveryPickupText: "عنوان الزبون، موقع المتجر وتتبع الطلب.",
    latestProducts: "منتجات جديدة",
    latestProductsSubtitle: "آخر المنتجات المضافة إلى المتجر",
    featuredProducts: "اختيارات AliShop",
    featuredProductsSubtitle: "منتجات مختارة من طرف فريقنا",
    promoProducts: "منتجات في العرض",
    promoProductsSubtitle: "عروض بأثمنة مخفضة",
    noActivePromos: "لا توجد عروض نشطة حاليا.",
    yourFavorites: "مفضلتك",
    yourFavoritesSubtitle: "المنتجات التي احتفظت بها قريبة منك",
    noFavoriteHome: "لا توجد لديك مفضلة بعد.",
    viewAll: "عرض الكل",
    noProductAvailable: "لا يوجد أي منتج متاح.",
    searchHero: "ابحث عن منتج أو قسم...",
    exploreProducts: "استكشف المنتجات",
    needHelp: "تحتاج مساعدة؟",
    deliveryPickup: "توصيل / استلام",
    catalogTitle: "اعثر على المنتج المناسب بسرعة.",
    catalogSubtitle: "تصفح الجديد والعروض والأقسام بتجربة سهلة على الهاتف.",
    filters: "الفلاتر",
    displayedProducts: "{count} منتج ظاهر",
    catalogCount: "تم العثور على {count} منتج",
    productsRange: "{from}-{to} من أصل {total} منتج",
    perPage: "{count} في الصفحة",
    removePromoFilter: "إزالة فلتر العروض",
    emptyCart: "سلتك فارغة",
    emptyCartDescription: "تصفح متجرنا وأضف المنتجات التي تعجبك. ستبقى اختياراتك محفوظة أثناء التسوق.",
    cartBenefitChoice: "منتجات وعروض مختارة",
    cartLoadError: "تعذر تحميل سلة التسوق",
    cartLoadErrorHelp: "تحقق من اتصالك ثم أعد المحاولة. لن يتم حذف أي منتج محفوظ.",
    quantityError: "تعذر تغيير الكمية",
    productRemoved: "تم حذف المنتج",
    seeProducts: "عرض المنتجات",
    viewDetails: "عرض التفاصيل",
    summary: "الملخص",
    subtotal: "المجموع الفرعي",
    estimatedDelivery: "توصيل تقديري",
    deliveryFee: "رسوم التوصيل",
    estimatedDeliveryFee: "تقدير التوصيل",
    deliveryDistance: "مسافة التوصيل",
    deliveryCalculatedCheckout: "يتم حساب رسوم التوصيل في صفحة إتمام الطلب حسب المسافة.",
    deliveryFeeEstimated: "30 درهم مجرد تقدير بدون GPS. فعّل موقعك لإظهار السعر الحقيقي للمسار.",
    deliveryFeeConfirmed: "تم حساب وتأكيد رسوم التوصيل: {fee} درهم.",
    deliveryDistancePrice: "المسار المحسوب: {distance} كم، الرسوم {fee} درهم.",
    freeDeliveryApplied: "تم تطبيق التوصيل المجاني من المتجر.",
    freeDeliveryProduct: "توصيل مجاني",
    freeDeliveryProductHint: "0 درهم إذا كانت السلة تحتوي فقط على منتجات مؤهلة.",
    pickupFree: "الاستلام من المتجر مجاني.",
    checkout: "إتمام الطلب",
    placeOrder: "تمرير الطلب",
    confirmOrder: "تأكيد الطلب",
    homeDelivery: "توصيل إلى المنزل",
    fulfillmentMode: "طريقة استلام الطلب",
    pickup: "استلام من المتجر",
    deliveryAddress: "عنوان التوصيل",
    addressRequired: "العنوان إلزامي",
    phoneRequired: "الهاتف إلزامي",
    fieldRequired: "حقل إلزامي",
    geolocationUnsupported: "تحديد الموقع غير مدعوم",
    locationError: "تعذر الحصول على موقعك",
    cmiRedirecting: "جار التحويل إلى دفع CMI الآمن",
    orderConfirmed: "تم تأكيد الطلب",
    checkoutError: "خطأ في إتمام الطلب",
    checkoutAccountTitle: "سجل الدخول لتأكيد الطلب",
    checkoutAccountText: "سلتك ستبقى هنا. سجل الدخول أو أنشئ حسابا، ثم سيتم تأكيد الطلب مباشرة.",
    continueAsLogin: "لدي حساب",
    continueAsRegister: "إنشاء حسابي",
    authAndOrder: "الدخول والطلب",
    registerAndOrder: "إنشاء الحساب والطلب",
    authRequiredCheckout: "سجل الدخول أو أنشئ حسابا لتأكيد الطلب.",
    customerOnlyCheckout: "فقط حساب الزبون يمكنه تمرير الطلب.",
    retryIn: "أعد المحاولة بعد {seconds}ث",
    useMyLocation: "استعمال موقعي للتوصيل",
    savedLocation: "تم حفظ الموقع",
    cashPayment: "الدفع عند الاستلام",
    cardPayment: "الدفع بالبطاقة",
    cmiSecure: "دفع آمن عبر CMI",
    cmiRedirect: "بعد التأكيد سيتم تحويلك إلى صفحة CMI البنكية للدفع بالبطاقة.",
    coupon: "كود التخفيض (اختياري)",
    supportClient: "دعم الزبناء",
    supportProblem: "مشكلة",
    requestProduct: "طلب منتج",
    productRequestSubject: "منتج مطلوب",
    wantedProductName: "اسم المنتج المطلوب",
    wantedProductPhoto: "صورة المنتج إن أمكن",
    supportTitle: "نحن هنا عندما يتوقف شيء ما.",
    supportSubtitle: "أرسل طلبك، تابع حالته وتوصل برد الإدارة مباشرة هنا.",
    priority: "الأولوية",
    low: "منخفضة",
    normal: "عادية",
    high: "مهمة",
    urgent: "مستعجلة",
    yourMessage: "رسالتك...",
    sending: "جار الإرسال...",
    sendMessage: "إرسال الرسالة",
    messageSent: "تم إرسال الرسالة. سنرد عليك بسرعة.",
    messageSendError: "تعذر إرسال الرسالة",
    supportLoadError: "تعذر تحميل طلبات الدعم",
    myRequests: "طلباتي",
    supportHistory: "سجل الدعم",
    loginToSeeSupport: "سجل الدخول لرؤية سجل طلبات الدعم.",
    noSupportMessages: "لا توجد طلبات حاليا.",
    supportReply: "رد الدعم",
    markResolved: "تحديد كمحلول",
    ticketClosed: "تم إغلاق الطلب",
    closeTicketError: "تعذر إغلاق هذا الطلب",
    open: "مفتوح",
    in_progress: "قيد المعالجة",
    answered: "تم الرد",
    closed: "مغلق",
    deliverySpace: "فضاء الموصّل",
    myDeliveries: "توصيلاتي",
    activeDeliveries: "{count} توصيلات نشطة",
    deliveryLoadError: "خطأ أثناء تحميل التوصيلات",
    loadingDeliveries: "جار تحميل التوصيلات...",
    noAssignedOrders: "لا يوجد أي طلب مخصص لك.",
    orderNumber: "طلب {id}",
    pending: "في الانتظار",
    preparing: "قيد التحضير",
    shipping: "في طريق التوصيل",
    delivered: "تم التوصيل",
    available: "متاح",
    contact: "التواصل",
    phoneUnavailable: "الهاتف غير متاح",
    openRoute: "فتح المسار",
    packageContent: "محتوى الطرد",
    missionAvailable: "المهمة متاحة لكل الموصلين. أول من يقبلها يأخذها.",
    acceptDelivery: "قبول هذا التوصيل",
    accepting: "جار القبول...",
    deliveryAccepted: "تم قبول التوصيل",
    deliveryUnavailable: "هذا التوصيل لم يعد متاحا",
    receiverName: "اسم المستلم",
    photoOnSite: "التقاط صورة في المكان",
    cameraOrGallery: "كاميرا الهاتف أو المعرض",
    deliveryNote: "ملاحظة التوصيل (اختيارية)",
    confirmDelivery: "تأكيد التوصيل",
    processing: "جار المعالجة...",
    deliveryConfirmed: "تم تأكيد التوصيل",
    deliveryDone: "تمت عملية التوصيل",
    proofRequired: "اسم المستلم والصورة في المكان إلزاميان",
    updateError: "خطأ في التحديث",
    orderTracking: "تتبع الزبون",
    loadOrdersError: "خطأ في تحميل الطلبات",
    noOrders: "لا توجد طلبات",
    storePickup: "استلام من المتجر",
    delivery: "توصيل",
    deliveryTracking: "تتبع التوصيل",
    received: "تم الاستلام",
    downloadReceipt: "تحميل الوصل PDF",
    receiptError: "تعذر تحميل الوصل",
    pickupInStore: "استلام من المتجر",
    deliveryProof: "دليل التوصيل",
    receivedBy: "استلمها: {name}",
    paymentConfirmed: "تم تأكيد الدفع",
    paymentNotConfirmed: "لم يتم تأكيد الدفع",
    paymentSuccessMessage: "تم تأكيد دفع CMI{order}.",
    paymentFailureMessage: "فشلت عملية الدفع بالبطاقة أو تم إلغاؤها. يمكنك مراجعة طلباتك أو إعادة الدفع.",
    forOrder: " للطلب #{id}",
    viewOrders: "عرض طلباتي",
    continueShopping: "متابعة التسوق",
    favoriteSelection: "اختياراتك",
    favoriteProducts: "المنتجات المفضلة",
    noFavorites: "لا توجد منتجات مفضلة حاليا.",
    loginTitle: "تسجيل الدخول",
    loginSubtitle: "استرجع سلتك وطلباتك ومفضلتك.",
    loginTrustText: "سلة محفوظة، طلبات آمنة، ودعم سريع.",
    forgotPassword: "نسيت كلمة المرور؟",
    loginAction: "دخول",
    loginLoading: "جار الدخول...",
    loginSuccess: "تم تسجيل الدخول بنجاح",
    loginError: "خطأ في تسجيل الدخول",
    noAccount: "ليس لديك حساب؟",
    createAccount: "إنشاء حساب",
    registerSubtitle: "سيتم الاحتفاظ بسلتك بعد إنشاء الحساب.",
    passwordConfirm: "تأكيد كلمة المرور",
    addressOptional: "العنوان (اختياري)",
    passwordTooShort: "كلمة المرور يجب أن تحتوي على 8 أحرف على الأقل",
    passwordMismatch: "كلمتا المرور غير متطابقتين",
    registerLoading: "جار الإنشاء...",
    accountCreated: "تم إنشاء الحساب بنجاح",
    registerError: "خطأ في التسجيل",
    alreadyAccount: "لديك حساب بالفعل؟",
    navigation: "التصفح",
    mainMenu: "القائمة الرئيسية",
    dashboard: "لوحة التحكم",
    categories: "الأقسام",
    users: "المستخدمون",
    adminAccount: "حساب الإدارة",
    adminSupportWorkflow: "تدبير رسائل الزبناء",
    adminSupportSubtitle: "رتب الأولوية، أجب وأغلق الطلبات من لوحة الإدارة.",
    supportUpdated: "تم تحديث الدعم",
    supportAdminLoadError: "تعذر تحميل الدعم",
    updateImpossible: "التحديث غير ممكن",
    lastReply: "آخر رد",
    writeCustomerReply: "اكتب ردا للزبون...",
    sendReply: "إرسال الرد",
    noCustomerMessage: "لا توجد رسائل زبناء.",
    profileUpdated: "تم تحديث الحساب",
    profileUpdateError: "خطأ أثناء تحديث الحساب",
    editProfile: "تعديل الحساب",
    changePassword: "تغيير كلمة المرور",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    showPasswords: "إظهار كلمات المرور",
    update: "تحديث",
    enterEmail: "المرجو إدخال البريد الإلكتروني",
    resetEmailSent: "تم إرسال بريد إعادة التعيين",
    resetPassword: "إعادة تعيين كلمة المرور",
    resetLoading: "جار إعادة التعيين...",
    passwordResetSuccess: "تمت إعادة تعيين كلمة المرور",
    resetError: "خطأ أثناء إعادة التعيين",
    send: "إرسال",
    yourEmail: "بريدك الإلكتروني",
    store: "المتجر",
    footerText: "متجر إلكتروني حديث في الدار البيضاء: عروض، استلام من المتجر، توصيل وتتبع الطلبات.",
    rightsReserved: "جميع الحقوق محفوظة.",
    cookieText: "نستعمل إحصائيات مجهولة لفهم المنتجات التي تمت زيارتها وتحسين الموقع.",
    accept: "قبول",
    decline: "رفض",
    gpsMissing: "لم يرسل الزبون موقع GPS.",
  },
};

const languageNames = {
  fr: "FR",
  en: "EN",
  ar: "AR",
};

const dateLocales = {
  fr: "fr-FR",
  en: "en-US",
  ar: "ar-MA",
};

function interpolate(text, params = {}) {
  return Object.entries(params).reduce(
    (value, [key, replacement]) => value.replaceAll(`{${key}}`, replacement ?? ""),
    text,
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export const LanguageContext = createContext({
  locale: "fr",
  dir: "ltr",
  languages: languageNames,
  setLocale: () => {},
  t: (key) => key,
  formatDate: (date) => date,
});

export function LanguageProvider({ children }) {
  const [locale, setLocaleState] = useState(() => {
    const savedLocale = String(localStorage.getItem("locale") || "fr").trim().toLowerCase();
    return dictionaries[savedLocale] ? savedLocale : "fr";
  });
  const dir = locale === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.dir = dir;
    localStorage.setItem("locale", locale);
  }, [locale, dir]);

  const value = useMemo(() => ({
    locale,
    dir,
    languages: languageNames,
    setLocale: (nextLocale) => {
      const normalizedLocale = String(nextLocale || "fr").trim().toLowerCase();
      setLocaleState(dictionaries[normalizedLocale] ? normalizedLocale : "fr");
    },
    t: (key, params) => interpolate(premium[locale]?.[key] || payment[locale]?.[key] || cash[locale]?.[key] || storefront[locale]?.[key] || dictionaries[locale]?.[key] || premium.fr[key] || payment.fr[key] || cash.fr[key] || storefront.fr[key] || dictionaries.fr[key] || key, params),
    formatDate: (date, options) => new Intl.DateTimeFormat(dateLocales[locale], options || { dateStyle: "medium", timeStyle: "short" }).format(new Date(date)),
  }), [locale, dir]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => useContext(LanguageContext);
